import os
base = '/a0/usr/projects/legalvu_v2/src'
files = {}

files['main/services/prompts.ts'] = 'export interface ContractPromptInput {\n  contractType: string;\n  counterparty: string;\n  jurisdiction: string;\n  keyTerms: string[];\n  indemnity: boolean;\n  confidentiality: boolean;\n  governingLaw: string;\n}\n\nexport function buildContractPrompt(input: ContractPromptInput): string {\n  return `Draft a ${input.contractType} for counterparty ${input.counterparty} under law of ${input.governingLaw}.\nKey terms:\n${input.keyTerms.map((t) => "- " + t).join("\\n")}\nInclude indemnity: ${input.indemnity}. Include confidentiality: ${input.confidentiality}.\nGenerate the full contract text in markdown. Only return the contract text.`;\n}\n'

files['main/services/ai-adapter.ts'] = "export interface AIProvider {\n  generateDraft(prompt: string, apiKey: string, model: string): Promise<string>;\n}\n\nexport class OpenAIAdapter implements AIProvider {\n  async generateDraft(prompt: string, apiKey: string, model: string): Promise<string> {\n    const res = await fetch('https://api.openai.com/v1/chat/completions', {\n      method: 'POST',\n      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },\n      body: JSON.stringify({ model, messages: [{ role: 'user', content: prompt }], temperature: 0.4 }),\n    });\n    if (!res.ok) throw new Error(`OpenAI error: ${res.statusText}`);\n    const data = await res.json() as { choices: { message: { content: string } }[] };\n    return data.choices[0].message.content;\n  }\n}\n\nexport class AnthropicAdapter implements AIProvider {\n  async generateDraft(prompt: string, apiKey: string, model: string): Promise<string> {\n    const res = await fetch('https://api.anthropic.com/v1/messages', {\n      method: 'POST',\n      headers: {\n        'Content-Type': 'application/json',\n        'x-api-key': apiKey,\n        'anthropic-version': '2023-06-01',\n      },\n      body: JSON.stringify({ model, max_tokens: 4096, messages: [{ role: 'user', content: prompt }] }),\n    });\n    if (!res.ok) throw new Error(`Anthropic error: ${res.statusText}`);\n    const data = await res.json() as { content: { type: string; text: string }[] };\n    return data.content[0].text;\n  }\n}\n\nexport function getProvider(provider: 'openai' | 'anthropic'): AIProvider {\n  return provider === 'anthropic' ? new AnthropicAdapter() : new OpenAIAdapter();\n}\n"

files['main/services/contract-service.ts'] = "import crypto from 'crypto';\nimport { getConnection } from '../database/connection';\nimport { getProvider } from './ai-adapter';\nimport { buildContractPrompt, type ContractPromptInput } from './prompts';\n\nexport async function createContractFromPrompt(\n  userId: string,\n  provider: 'openai' | 'anthropic',\n  apiKey: string,\n  model: string,\n  input: ContractPromptInput,\n): Promise<string> {\n  const db = getConnection();\n  const ai = getProvider(provider);\n  const prompt = buildContractPrompt(input);\n  const draft = await ai.generateDraft(prompt, apiKey, model);\n  const id = crypto.randomUUID();\n  const now = Date.now();\n  db.prepare(\n    `INSERT INTO contracts (id, title, status, counterparty, jurisdiction, content, ai_prompt_version, ai_model, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`\n  ).run(id, `${input.contractType} - ${input.counterparty}`, 'draft', input.counterparty, input.jurisdiction, draft, JSON.stringify(input), model, userId, now, now);\n  return id;\n}\n\nexport function getContract(id: string): Record<string, unknown> | undefined {\n  const db = getConnection();\n  return db.prepare('SELECT * FROM contracts WHERE id = ?').get(id) as Record<string, unknown> | undefined;\n}\n"

files['renderer/stores/contract-store.ts'] = "import { create } from 'zustand';\n\ninterface ContractState {\n  draft: string | null;\n  isLoading: boolean;\n  error: string | null;\n  setDraft: (draft: string) => void;\n  setLoading: (loading: boolean) => void;\n  setError: (error: string | null) => void;\n}\n\nexport const useContractStore = create<ContractState>((set) => ({\n  draft: null,\n  isLoading: false,\n  error: null,\n  setDraft: (draft) => set({ draft }),\n  setLoading: (isLoading) => set({ isLoading }),\n  setError: (error) => set({ error }),\n}));\n"

files['renderer/App.tsx'] = "import React from 'react';\n\nfunction App() {\n  return (\n    <div className=\"min-h-screen bg-gray-100 p-4\">\n      <h1 className=\"text-2xl font-bold mb-4\">Legal Workspace</h1>\n      <p className=\"text-gray-600\">AI contract drafting and SharePoint integration</p>\n    </div>\n  );\n}\n\nexport default App;\n"

for rel, content in files.items():
    full = os.path.join(base, rel)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, 'w') as f:
        f.write(content)

print('Phase3 files written')
